custom_postgres:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: destination_postgres
      port: 5432
      user: postgres
      pass: secret
      dbname: destination_db
      schema: public
  target: dev