version: '3'

services:
  source_postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  postgres:
    image: postgres:15
    networks:
      - elt_network
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data

  # Airbyte Services
  airbyte-db:
    image: postgres:15
    networks:
      - elt_network
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=airbyte
    volumes:
      - airbyte_db:/var/lib/postgresql/data

  airbyte-server:
    image: airbyte/server:0.63.15
    ports:
      - "8001:8001"
    networks:
      - elt_network
    environment:
      - DATABASE_HOST=airbyte-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=docker
      - DATABASE_USER=docker
      - DATABASE_DB=airbyte
      - WEBAPP_URL=http://localhost:8000
      - WORKER_ENVIRONMENT=docker
      - WORKSPACE_ROOT=/tmp/workspace
      - WORKSPACE_DOCKER_MOUNT=airbyte_workspace
      - LOCAL_ROOT=/tmp/airbyte_local
      - LOCAL_DOCKER_MOUNT=/tmp/airbyte_local
      - CONFIG_ROOT=/data
      - TRACKING_STRATEGY=logging
    volumes:
      - airbyte_workspace:/tmp/workspace
      - airbyte_data:/data
      - airbyte_local:/tmp/airbyte_local
    depends_on:
      - airbyte-db

  airbyte-webapp:
    image: airbyte/webapp:0.63.15
    ports:
      - "8000:80"
    networks:
      - elt_network
    environment:
      - AIRBYTE_ROLE=webapp
      - AIRBYTE_VERSION=0.63.15
      - API_URL=/api/v1/
      - IS_DEMO=false
      - PAPERCUPS_STORYTIME=disabled
      - TRACKING_STRATEGY=logging
    depends_on:
      - airbyte-server

  airbyte-worker:
    image: airbyte/worker:0.63.15
    networks:
      - elt_network
    environment:
      - AIRBYTE_VERSION=0.63.15
      - AUTO_DETECT_SCHEMA=true
      - DATABASE_HOST=airbyte-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=docker
      - DATABASE_USER=docker
      - DATABASE_DB=airbyte
      - WORKSPACE_ROOT=/tmp/workspace
      - WORKSPACE_DOCKER_MOUNT=airbyte_workspace
      - LOCAL_ROOT=/tmp/airbyte_local
      - LOCAL_DOCKER_MOUNT=/tmp/airbyte_local
      - CONFIG_ROOT=/data
      - TRACKING_STRATEGY=logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - airbyte_workspace:/tmp/workspace
      - airbyte_data:/data
      - airbyte_local:/tmp/airbyte_local
    depends_on:
      - airbyte-server

  airbyte:
    image: airbyte/server:0.63.15
    ports:
      - "8006:8006"
    networks:
      - elt_network
    environment:
      - AIRBYTE_ROLE=server
      - DATABASE_HOST=airbyte-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=docker
      - DATABASE_USER=docker
      - DATABASE_DB=airbyte
    depends_on:
      - airbyte-db
      - airbyte-server

  airflow:
    build: 
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - postgres
    networks:
      - elt_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./elt:/opt/airflow/elt
      - ./custom_postgres:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=mjWiVpufCtoTLmthnugkJ0xhRBb9MUlBqmvjIuJi3Lc=
    ports:
      - "8080:8080"
    command: bash -c "sleep 10 && airflow db reset --yes && airflow users create --username airflow --password password --firstname Sachin --lastname Shet --role Admin --email sachin@example.com && airflow standalone"

volumes:
  postgres_db_volume:
  airbyte_db:
  airbyte_workspace:
  airbyte_data:
  airbyte_local:

networks:
  elt_network:
    driver: bridge