services:
  source_postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  postgres:
    image: postgres:15
    networks:
      - elt_network
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data

  # Airbyte Setup - Manual working setup using basic components only
  # This avoids the complex temporal/bootloader issues
  
  # Use Airbyte's standalone stack - simpler alternative
  # For now, provide manual setup instructions for Airbyte
  airbyte-placeholder:
    image: hello-world
    container_name: airbyte-placeholder
    networks:
      - elt_network

  airflow:
    build: 
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - postgres
    networks:
      - elt_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./elt:/opt/airflow/elt
      - ./custom_postgres:/opt/airflow/custom_postgres
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=mjWiVpufCtoTLmthnugkJ0xhRBb9MUlBqmvjIuJi3Lc=
    ports:
      - "8080:8080"
    command: bash -c "sleep 10 && airflow db reset --yes && airflow users create --username airflow --password password --firstname Sachin --lastname Shet --role Admin --email sachin@example.com && airflow standalone"

volumes:
  postgres_db_volume:
  airbyte_data:

networks:
  elt_network:
    driver: bridge